import exchange from "../exchange.js";

describe("filterRows", () => {
  test("filter for XTZ", () => {
    // cover trade:fiat-out, transfer, receive, trade
    // filter out one uninvolved coin
    const rows = [
      {
        account: "coinbase",
        fiat: 3,
        in_amt: 50000,
        in_token: "XTZ",
        in_token_from: "coinbase",
        in_token_id: undefined,
        out_amt: 150000,
        out_token: "USD",
        out_token_id: undefined,
        out_token_to: "coinbase",
        type: "trade:fiat-out",
      },
      {
        account: "coinbase",
        fiat: 0.001,
        in_amt: 50000,
        in_token: "DOGE",
        in_token_from: "external",
        in_token_id: undefined,
        out_amt: undefined,
        out_token: undefined,
        out_token_id: undefined,
        out_token_to: undefined,
        type: "receive",
      },
      {
        account: "coinbase",
        fiat: 0.2,
        in_amt: 100,
        in_token: "XLM",
        in_token_from: "external",
        in_token_id: undefined,
        out_amt: undefined,
        out_token: undefined,
        out_token_id: undefined,
        out_token_to: undefined,
        type: "receive",
      },
      {
        account: "coinbase",
        fiat: 0.2,
        in_amt: 50,
        in_token: "XTZ",
        in_token_from: "coinbase",
        in_token_id: undefined,
        out_amt: 10,
        out_token: "XLM",
        out_token_id: undefined,
        out_token_to: "coinbase",
        type: "trade",
      },
      {
        account: "coinbase",
        in_amt: 0,
        in_token: undefined,
        in_token_from: undefined,
        in_token_id: undefined,
        out_amt: 10,
        out_token: "XTZ",
        out_token_id: undefined,
        out_token_to: "tz123",
        type: "transfer",
      },
      {
        account: "coinbase",
        fiat: 3,
        in_amt: 50000,
        in_token: "DOGE",
        in_token_from: "coinbase",
        in_token_id: undefined,
        out_amt: 150000,
        out_token: "ETH",
        out_token_id: undefined,
        out_token_to: "coinbase",
        type: "trade",
      },
      {
        account: "coinbase",
        fiat: 3,
        in_amt: 50000,
        in_token: "BTC",
        in_token_from: "coinbase",
        in_token_id: undefined,
        out_amt: 150000,
        out_token: "XTZ",
        out_token_id: undefined,
        out_token_to: "coinbase",
        type: "trade",
      },
    ];

    expect(exchange.filterRows(rows)).toStrictEqual([
      {
        account: "coinbase",
        fiat: 3,
        in_amt: 50000,
        in_token: "XTZ",
        in_token_from: "coinbase",
        in_token_id: undefined,
        out_amt: 150000,
        out_token: "USD",
        out_token_id: undefined,
        out_token_to: "coinbase",
        type: "trade:fiat-out",
      },
      {
        account: "coinbase",
        fiat: 0.2,
        in_amt: 100,
        in_token: "XLM",
        in_token_from: "external",
        in_token_id: undefined,
        out_amt: undefined,
        out_token: undefined,
        out_token_id: undefined,
        out_token_to: undefined,
        type: "receive",
      },
      {
        account: "coinbase",
        fiat: 0.2,
        in_amt: 50,
        in_token: "XTZ",
        in_token_from: "coinbase",
        in_token_id: undefined,
        out_amt: 10,
        out_token: "XLM",
        out_token_id: undefined,
        out_token_to: "coinbase",
        type: "trade",
      },
      {
        account: "coinbase",
        in_amt: 0,
        in_token: undefined,
        in_token_from: undefined,
        in_token_id: undefined,
        out_amt: 10,
        out_token: "XTZ",
        out_token_id: undefined,
        out_token_to: "tz123",
        type: "transfer",
      },
      {
        account: "coinbase",
        fiat: 3,
        in_amt: 50000,
        in_token: "BTC",
        in_token_from: "coinbase",
        in_token_id: undefined,
        out_amt: 150000,
        out_token: "XTZ",
        out_token_id: undefined,
        out_token_to: "coinbase",
        type: "trade",
      },
    ]);
  });
});
